@extends('layout')

@section('title', 'Account Security & Upwork Compliance Policy — FirstBidIn')

@section('content')
<div style="max-width: 820px; margin: 0 auto 50px;">
  <div class="glass-panel" style="padding: 40px; background: #ffffff;">
    <div style="font-size: 11px; font-family: var(--font-mono); color: var(--upwork-green); font-weight: 800; text-transform: uppercase; margin-bottom: 8px;">
      🛡️ ZERO RISK ACCOUNT PROTECTION
    </div>
    
    <h1 style="font-size: 32px; font-weight: 800; color: var(--text-dark); margin-bottom: 12px; letter-spacing: -0.02em;">
      Account Security & Upwork ToS Compliance Policy
    </h1>
    
    <div style="font-size: 13px; color: var(--text-muted); margin-bottom: 28px; border-bottom: 1px solid var(--border); padding-bottom: 16px;">
      Effective Date: <strong>August 9, 2026</strong> · Upwork ToS Compliant
    </div>

    <div style="font-size: 15px; color: var(--text-main); line-height: 1.75; display: flex; flex-direction: column; gap: 20px;">
      <p>
        At <strong>FirstBidIn</strong>, protecting your freelancer account reputation and ensuring strict adherence to freelance marketplace Terms of Service is our top priority.
      </p>

      <h2 style="font-size: 20px; font-weight: 800; color: var(--text-dark); margin-top: 10px;">1. Strict Human-in-the-Loop Writing Assistance</h2>
      <p>
        FirstBidIn is engineered exclusively as a proposal drafting assistant. We do <strong>NOT</strong> operate auto-bidding bots, background application scrapers, or automated proposal submission scripts. Every proposal generated by FirstBidIn requires manual review, editing, and single-click submission by the user.
      </p>

      <h2 style="font-size: 20px; font-weight: 800; color: var(--text-dark); margin-top: 10px;">2. Zero Third-Party API Token Storage</h2>
      <p>
        FirstBidIn never asks for, stores, or accesses your Upwork login credentials, session cookies, or account passwords. Your freelancer account remains 100% in your control at all times.
      </p>

      <h2 style="font-size: 20px; font-weight: 800; color: var(--text-dark); margin-top: 10px;">3. Native Extension & Webhook Isolation</h2>
      <p>
        Our Chrome Browser Extension operates locally in your browser (Manifest V3) using isolated webhooks and RSS feeds. It injects a helper workspace overlay directly on client job pages without modifying or scraping sensitive account data.
      </p>

      <h2 style="font-size: 20px; font-weight: 800; color: var(--text-dark); margin-top: 10px;">4. Data Privacy & Encryption</h2>
      <p>
        All communications between your browser, the FirstBidIn Web app, and AI models are encrypted in transit via SSL/TLS 1.3. We never share your portfolio projects, hourly rates, or proposal drafts with third parties.
      </p>

      <h2 style="font-size: 20px; font-weight: 800; color: var(--text-dark); margin-top: 10px;">5. Security Audits & Inquiries</h2>
      <p>
        For security questions or compliance inquiries, reach out to our security team at <a href="mailto:security@firstbidin.com" style="color: var(--upwork-green); font-weight: 700;">security@firstbidin.com</a>.
      </p>
    </div>
  </div>
</div>
@endsection
